typography_spectrum: 0.0724
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.5
  lightness: 0.9984897819813341
  saturation: 0.0018578290473669767
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: chrisreedjr
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Audio Stuff
purpose: []
